// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yofljtzvdskjvpyuqvdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvZmxqdHp2ZHNranZweXVxdmRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5ODU1OTksImV4cCI6MjA1OTU2MTU5OX0.udbuTPPFyzSv95D85q1csSceV_LuY8uwaTlO8CAiSzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);